### ISSUE TITLE
Crash while removing multiple images

### ISSUE THREAD

**Issue by volodymyr-vestasoft** [Soulghost/SGPhotoBrowser#1]
```
    [self setDeleteHandlerBlock:^(NSInteger index) {
        [weakSelf.photoModels removeObjectAtIndex:index];
```

Index out of bounds. I think it's better to pass array of SGPhotoModel's to deleteHandler.

**Comment by Soulghost** [comment]
That's a good idea, multiple delete makes the index of model wrong, I'll fix it.

**Comment by Soulghost** [comment]
Now the **deleteHandler** will return an **NSIndexSet**, you can use **NSMutableArray**'s method **removeObjectsAtIndexes:** to remove models at once, and then call the reload method.
